title: Homepage of KunalOS
description: "A place to share my learning journey in the field of machine and deep learning"
author:
  name: "KunalOS"
  email: "rustagi.kunal@outlook.com"
  url: "https://kunalrustagi08.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "KunalOS"
year : "2020"
